version: "3.8"

services:
  flask-app:
    build:
      context: ../flask-app  
    image: my-flask-app:latest  
    container_name: flask-app
    ports:
      - "5141:5141"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: ["-config.file=/etc/promtail/config.yaml"]



  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    ports:
      - "3200:3200"  
      - "4316:4317"  
      - "4319:4318"  
    volumes:
      - ./tempo-config.yaml:/etc/tempo-config.yaml
      - tempo-data:/var/tempo/traces  
    command: ["-config.file=/etc/tempo-config.yaml"]
    


  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.81.0
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "4317:4317"
      - "4318:4318"

volumes:
  tempo-data:  

