name: Terraform & Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init & Plan
        run: |
          cd terraform
          terraform init
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
        if: github.ref == 'refs/heads/main'

  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/flask-app:${{ github.sha }} -f flask-app/Dockerfile flask-app
          docker push ghcr.io/${{ github.repository }}/flask-app:${{ github.sha }}

  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Deploy Flask App
        run: |
          kubectl set image deployment/flask-app flask-app=ghcr.io/${{ github.repository }}/flask-app:${{ github.sha }} -n observability
